# -*- coding: <UTF-8> -*-
from Card import *
import renpy.store as store
import renpy.exports as renpy

deck_man_standart = []
deck_man_standart.append(Card("Kiss"))
deck_man_standart.append(Card("Fondle"))
deck_man_standart.append(Card("Lick"))
deck_man_standart.append(Card("Massage"))
deck_man_standart.append(Card("Gentle penetration"))
deck_man_standart.append(Card("Gentle penetration"))
deck_man_standart.append(Card("Forceful penetration"))
deck_man_standart.append(Card("Forceful penetration"))
deck_man_standart.append(Card("Forceful penetration"))
deck_man_standart.append(Card("Jerk"))
deck_man_standart.append(Card("Bite"))
deck_man_standart.append(Card("Slap"))
deck_man_standart.append(Card("Dirty-talk"))
deck_man_standart.append(Card("From behind"))
deck_man_standart.append(Card("On top"))
deck_man_standart.append(Card("Side pose"))
deck_man_standart.append(Card("Sixty-nine"))
deck_man_standart.append(Card("Golden shower"))
deck_man_standart.append(Card("Dominance"))
deck_man_standart.append(Card("Passion"))
deck_man_standart.append(Card("Brutality"))
deck_man_standart.append(Card("Cruelty"))

deck_woman_standart = []
deck_woman_standart.append(Card("Kiss"))
deck_woman_standart.append(Card("Fondle"))
deck_woman_standart.append(Card("Lick"))
deck_woman_standart.append(Card("Massage"))
deck_woman_standart.append(Card("Suck"))
deck_woman_standart.append(Card("Suck"))
deck_woman_standart.append(Card("Sloppy sounds"))
deck_woman_standart.append(Card("Jerk"))
deck_woman_standart.append(Card("Scratch"))
deck_woman_standart.append(Card("Pinch"))
deck_woman_standart.append(Card("Passiveness"))
deck_woman_standart.append(Card("Doggy-style"))
deck_woman_standart.append(Card("Under"))
deck_woman_standart.append(Card("Side pose"))
deck_woman_standart.append(Card("Sixty-nine"))
deck_woman_standart.append(Card("Foot worship"))
deck_woman_standart.append(Card("Soft maso"))
deck_woman_standart.append(Card("Psi-maso"))
deck_woman_standart.append(Card("Submission"))
deck_woman_standart.append(Card("Tenderness"))
deck_woman_standart.append(Card("Hysteria"))
deck_woman_standart.append(Card("Laceration"))