# -*- coding: <UTF-8> -*-
from Card import *
import renpy.store as store
import renpy.exports as renpy

# Preconstracted decks for use in game

deck_man_standart = []
deck_man_standart.append(Card("Kiss"))
deck_man_standart.append(Card("Fondle"))
deck_man_standart.append(Card("Lick"))
deck_man_standart.append(Card("Massage"))
deck_man_standart.append(Card("Gentle hip moves"))
deck_man_standart.append(Card("Gentle hip moves"))
deck_man_standart.append(Card("Forceful hip moves"))
deck_man_standart.append(Card("Forceful hip moves"))
deck_man_standart.append(Card("Forceful hip moves"))
deck_man_standart.append(Card("Jerk"))
deck_man_standart.append(Card("Bite"))
deck_man_standart.append(Card("Slap"))
deck_man_standart.append(Card("Dirty-talk"))
deck_man_standart.append(Card("From behind"))
deck_man_standart.append(Card("On top"))
deck_man_standart.append(Card("Side pose"))
deck_man_standart.append(Card("Sixty-nine"))
deck_man_standart.append(Card("Golden shower"))
deck_man_standart.append(Card("Dominance"))
deck_man_standart.append(Card("Passion"))
deck_man_standart.append(Card("Brutality"))
deck_man_standart.append(Card("Cruelty"))

deck_woman_standart = []
deck_woman_standart.append(Card("Kiss"))
deck_woman_standart.append(Card("Fondle"))
deck_woman_standart.append(Card("Lick"))
deck_woman_standart.append(Card("Massage"))
deck_woman_standart.append(Card("Suck"))
deck_woman_standart.append(Card("Suck"))
deck_woman_standart.append(Card("Sloppy sounds"))
deck_woman_standart.append(Card("Jerk"))
deck_woman_standart.append(Card("Scratch"))
deck_woman_standart.append(Card("Pinch"))
deck_woman_standart.append(Card("Passiveness"))
deck_woman_standart.append(Card("Doggy-style"))
deck_woman_standart.append(Card("Under"))
deck_woman_standart.append(Card("Side pose"))
deck_woman_standart.append(Card("Sixty-nine"))
deck_woman_standart.append(Card("Foot worship"))
deck_woman_standart.append(Card("Soft maso"))
deck_woman_standart.append(Card("Psi-maso"))
deck_woman_standart.append(Card("Submission"))
deck_woman_standart.append(Card("Tenderness"))
deck_woman_standart.append(Card("Hysteria"))
deck_woman_standart.append(Card("Laceration"))

deck_rapist = []
deck_rapist.append(Card("Scratch"))
deck_rapist.append(Card("Bite"))
deck_rapist.append(Card("Pinch"))
deck_rapist.append(Card("Slap"))
deck_rapist.append(Card("Slap"))
deck_rapist.append(Card("Dirty-talk"))
deck_rapist.append(Card("Dirty-talk"))
deck_rapist.append(Card("Forceful hip moves"))
deck_rapist.append(Card("Forceful hip moves"))
deck_rapist.append(Card("Forceful hip moves"))
deck_rapist.append(Card("Lick"))
deck_rapist.append(Card("On top"))
deck_rapist.append(Card("From behind"))
deck_rapist.append(Card("Jerk"))
deck_rapist.append(Card("Jerk"))
deck_rapist.append(Card("Sadism"))
deck_rapist.append(Card("Mockery"))
deck_rapist.append(Card("Frenzy"))
deck_rapist.append(Card("Dominance"))
deck_rapist.append(Card("Passion"))
deck_rapist.append(Card("Brutality"))
deck_rapist.append(Card("Cruelty"))

deck_virgin = []
deck_virgin.append(Card("Scratch"))
deck_virgin.append(Card("Scratch"))
deck_virgin.append(Card("Pinch"))
deck_virgin.append(Card("Bite"))
deck_virgin.append(Card("Bite"))
deck_virgin.append(Card("Bite"))
deck_virgin.append(Card("Slap"))
deck_virgin.append(Card("Slap"))
deck_virgin.append(Card("Forceful hip moves"))
deck_virgin.append(Card("Pinch"))
deck_virgin.append(Card("Dirty-talk"))
deck_virgin.append(Card("Dirty-talk"))
deck_virgin.append(Card("Frenzy"))
deck_virgin.append(Card("Passiveness"))
deck_virgin.append(Card("Passiveness"))
deck_virgin.append(Card("Passiveness"))
deck_virgin.append(Card("Doggy-style"))
deck_virgin.append(Card("Hysteria"))
deck_virgin.append(Card("Laceration"))
deck_virgin.append(Card("Under"))
deck_virgin.append(Card("Sloppy sounds"))
deck_virgin.append(Card("Sloppy sounds"))

deck_whore = []
deck_whore.append(Card("Kiss"))
deck_whore.append(Card("Lick"))
deck_whore.append(Card("Lick"))
deck_whore.append(Card("Suck"))
deck_whore.append(Card("Suck"))
deck_whore.append(Card("Fondle"))
deck_whore.append(Card("Fondle"))
deck_whore.append(Card("Massage"))
deck_whore.append(Card("Gentle hip moves"))
deck_whore.append(Card("Gentle hip moves"))
deck_whore.append(Card("Gentle hip moves"))
deck_whore.append(Card("Gentle hip moves"))
deck_whore.append(Card("Forceful hip moves"))
deck_whore.append(Card("Sloppy sounds"))
deck_whore.append(Card("Dirty-talk"))
deck_whore.append(Card("Age-play"))
deck_whore.append(Card("Foot worship"))
deck_whore.append(Card("Frenzy"))
deck_whore.append(Card("Tenderness"))
deck_whore.append(Card("Tenderness"))
deck_whore.append(Card("Submission"))
deck_whore.append(Card("Enslavement"))

deck_succubus = []
deck_succubus.append(Card("Kiss"))
deck_succubus.append(Card("Lick"))
deck_succubus.append(Card("Fondle"))
deck_succubus.append(Card("Suck"))
deck_succubus.append(Card("Suck"))
deck_succubus.append(Card("Suck"))
deck_succubus.append(Card("Massage"))
deck_succubus.append(Card("Frenzy"))
deck_succubus.append(Card("Frenzy"))
deck_succubus.append(Card("Frenzy"))
deck_succubus.append(Card("Tenderness"))
deck_succubus.append(Card("Tenderness"))
deck_succubus.append(Card("Gentle hip moves"))
deck_succubus.append(Card("Gentle hip moves"))
deck_succubus.append(Card("Forceful hip moves"))
deck_succubus.append(Card("Forceful hip moves"))
deck_succubus.append(Card("Forceful hip moves"))
deck_succubus.append(Card("Sixty-nine"))
deck_succubus.append(Card("Sixty-nine"))
deck_succubus.append(Card("Under"))
deck_succubus.append(Card("From behind"))
deck_succubus.append(Card("Side pose"))